cc_library(
    name = "leaking-bucket-lib",
    hdrs = ["leaking-bucket-algo.h"],
)

cc_binary(
    name = "leaking-bucket-algo",
    srcs = ["leaking-bucket-algo.cpp"],
    deps = [":leaking-bucket-lib"],
)
